services:
  postgres:
    image: postgres:13.4-alpine
    container_name: postgres_dev_parq_core
    ports:
      - "${POSTGRES_PORT:-5444}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: parq_core
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    name: pg_data_parq_core
